name: Build macOS JAR

on: [workflow_dispatch]

jobs:
  build:
    runs-on: macos-14

    steps:
    - name: Checkout
      uses: actions/checkout@v6
      with:
        submodules: true

    - name: Install JDK
      uses: actions/setup-java@v5
      with:
        distribution: temurin
        java-version: "17"

    - name: Build
      run: ./build.sh host-jar "release"

    - name: Save
      uses: actions/upload-artifact@v7
      with:
        archive: false
        path: dist/*-jar-release/pkg/*.jar
